"""
This type stub file was generated by pyright.
"""

class _NDFrameIndexerBase:
    def __init__(self, name: str, obj: object) -> None:
        ...
    
    @property
    def ndim(self) -> int:
        ...
    


