"""
This type stub file was generated by pyright.
"""

from pandas._typing import Dtype, Scalar, npt
from pandas.core.dtypes.base import ExtensionDtype

class SparseDtype(ExtensionDtype):
    def __init__(self, dtype: Dtype | npt.DTypeLike = ..., fill_value: Scalar | None = ...) -> None:
        ...
    
    @property
    def fill_value(self) -> Scalar | None:
        ...
    


